[package]
name = "arcdps_apm"
version = "0.1.0"
edition = "2021"
authors = ["Zerthox"]
repository = "https://github.com/zerthox/arcdps-apm"

[dependencies]
arcdps = "0.7"
arcdps-imgui = "0.8"
arc_util = { git = "https://github.com/zerthox/arcdps-utils", branch = "0.7.x", features = ["serde", "settings"] }
once_cell = "1.9"
windows = "0.37"

[lib]
crate-type = ["cdylib"]
