[env]
GW2_PATH = { value = "C:/Program Files/Guild Wars 2", condition = { env_not_set = ["GW2_PATH"] } }
GW2_ADDON_MANAGER = { value = "true", condition = { files_exist = ["${GW2_PATH}/addons/arcdps/gw2addon_arcdps.dll"] } }

[env.ARCDPS_PATH]
default_value = "${GW2_PATH}/bin64"
source = "${GW2_ADDON_MANAGER}"
mapping = { true = "${GW2_PATH}/addons/arcdps" }
condition = { env_not_set = ["ARCDPS_PATH"] }

[tasks.build]
script = "cargo build --release"
clear = true

[tasks.copy]
script = "cp \"${CARGO_MAKE_CRATE_TARGET_DIRECTORY}/release/${CARGO_MAKE_CRATE_NAME}.dll\" \"${ARCDPS_PATH}\""
script_runner = "@shell"

[tasks.remove]
script = "rm \"${ARCDPS_PATH}/${CARGO_MAKE_CRATE_NAME}.dll\""
script_runner = "@shell"

[tasks.install]
run_task = { name = ["build", "copy"] }

[tasks.uninstall]
alias = "remove"
